# Generated by Django 3.2.10 on 2023-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20230330_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(blank=True, default='images/profile/defualts/defualt_background.png', null=True, upload_to='images/profile/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/defualts/defualt_profile.png', null=True, upload_to='images/profile/profile_pictures'),
        ),
    ]
